# Generated by Django 3.1.4 on 2021-02-24 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210224_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public_day',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
