# Generated by Django 3.1.4 on 2021-02-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210224_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_origin',
            field=models.FloatField(null=True),
        ),
    ]
