# Generated by Django 4.0.4 on 2023-01-04 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_category_id_alter_client_id_alter_customer_id_and_more'),
        ('khachhang', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngaydathang', models.DateField()),
                ('httt', models.CharField(max_length=50)),
                ('diachigiaohang', models.CharField(max_length=250)),
                ('tongtien', models.FloatField()),
                ('tamung', models.FloatField()),
                ('conlai', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='CTDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soluong', models.PositiveIntegerField(default=1)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhang_items', to='khachhang.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanpham_items', to='store.product')),
            ],
        ),
    ]
